CREATE TABLE IF NOT EXISTS `knowledge`.`snippet` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(200) NULL DEFAULT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `language` VARCHAR(45) NULL DEFAULT NULL,
  `gmt_create` TIMESTAMP NULL DEFAULT NULL,
  `gmt_modify` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `knowledge`.`faq` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(1000) NULL DEFAULT NULL,
  `answer` VARCHAR(2000) NULL DEFAULT NULL,
  `tag` VARCHAR(200) NULL DEFAULT NULL,
  `categ` VARCHAR(45) NULL DEFAULT NULL,
  `gmt_create` TIMESTAMP NULL DEFAULT NULL,
  `gmt_modify` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `knowledge`.`frame_notice` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `tag` VARCHAR(200) NULL DEFAULT NULL,
  `caution` VARCHAR(2000) NULL DEFAULT NULL,
  `categ` VARCHAR(45) NULL DEFAULT NULL,
  `gmt_create` TIMESTAMP NULL DEFAULT NULL,
  `gmt_modify` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `knowledge`.`notion` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL DEFAULT NULL,
  `explain` VARCHAR(1000) NULL DEFAULT NULL,
  `tag` VARCHAR(200) NULL DEFAULT NULL,
  `categ` VARCHAR(45) NULL DEFAULT NULL,
  `gmt_create` TIMESTAMP NULL DEFAULT NULL,
  `gmt_modify` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;